### ISSUE TITLE
Defining outer borders

### ISSUE THREAD

**Issue by prusaframe** [bonafid3/Voronoi#1]
Hi,

Thanks for the code, useful work! I am not a coder myself, but I was wondering whether the tool could be adapted slightly. I would like to define a framework in units before executing the program. This would force the program to plot a Voronoi pattern within the given borders and prevents the box from varying in size, which seems to be the case in your current version. This way, adjusting the size of the polygons is much easier by increasing or decreasing the number of 'boxes' in the horizontal and vertical direction, while the area of the canvas remains constant. Hopefully it won't take too much effort for you to achieve this.

Thanks a lot!

**Comment by bonafid3** [comment]
Hi,

I know it is an old issue and I had other things to do, but I needed something similar, so I made an update. The code updated, and available now. Better late than never.
